### ISSUE TITLE
Replace javascript date fields with html input type="date"

### ISSUE THREAD

**Issue by nathangeffen** [groundupnews/gu#19]
- Replace javascript date fields with html input type="date"
  - https://www.groundup.org.za/advanced_search/?adv_search=&search_type=article&is_simple=true
  - https://www.groundup.org.za/generate_article_list/
  - https://www.groundup.org.za/judgment/
  - Possibly here: https://www.groundup.org.za/article/[SLUG] in edit mode (To be discussed)
  - Possibly here: https://www.groundup.org.za/invoices/[0-9]-[0-9] (To be discussed)
  - Possibly here: https://www.groundup.org.za/commissions/analysis (To be discussed)

**Comment by goyal1092** [comment]
PR: https://github.com/groundupnews/gu/pull/22

**Comment by nathangeffen** [comment]
In production
