### ISSUE TITLE
Gallery page redesign

### ISSUE THREAD

**Issue by nathangeffen** [groundupnews/gu#20]
The Gallery page needs work and redesign - https://www.groundup.org.za/imagegallery/ (To be discussed)

Including: Remove awful infinite scrolling "feature" on https://www.groundup.org.za/imagegallery/photo/[0-9]/
and replace with standard pager like on all our other list pages

**Comment by goyal1092** [comment]
PR: https://github.com/groundupnews/gu/pull/23

**Comment by nathangeffen** [comment]
Compare https://www.groundup.org.za/imagegallery/photos/ (with the old code) to the version on your local machine after the update. The photos are not displaying with the new version.
